MOST_EVIL_PRICE_PLAN_ID = "price-plan-0"
RENEWBLES_PRICE_PLAN_ID = "price-plan-1"
STANDARD_PRICE_PLAN_ID = "price-plan-2"

NUM_METERS = 10
NUM_READINGS_AGAINST_METER = 50

MOST_EVIL_PRICE_PLAN_ID_UNIT_RATE = 10
RENEWBLES_PRICE_PLAN_ID_UNIT_RATE = 2
STANDARD_PRICE_PLAN_ID_UNIT_RATE = 1
